# Generated by Django 4.2.2 on 2024-01-14 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("admission_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admissions",
            name="insurance",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="admission_management.insurances",
            ),
        ),
    ]
