# Generated by Django 4.2.2 on 2024-01-15 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admission_management", "0002_alter_admissions_insurance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diagnoses",
            name="diag_description",
            field=models.TextField(null=True),
        ),
    ]
